server:
  port: 8081
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test5
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      max-lifetime: 30000
      connection-timeout: 60000
      pool-name: testHikariPool